name: Test Workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16' # Defina a versão do Node.js desejada aqui

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
